name: Run tests

env:
  TEMPLATEDIR: ${HOME}/.texlive/texmf-local/tex/latex/latex-template

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        sudo apt-get install imagemagick librsvg2-bin
        pip install Pygments
    - name: Use cache
      id: cache-install
      uses: actions/cache@v3
      with:
        path: |
          ${HOME}/.texlive
        key: texlive
    - name: Set up TeXLive
      run: |
        ./scripts/install_font.sh
        ./scripts/install_texlive.sh
        echo "PATH=${HOME}/.texlive/bin/x86_64-linux:$PATH" >> $GITHUB_ENV
    - name: Test Lua
      run: |
        cd tests
        make lua-test
    - name: Test LaTeX
      run: |
        mkdir -p ${{ env.TEMPLATEDIR }}
        cp -r * ${{ env.TEMPLATEDIR }}
        texhash
        cd tests
        make author-test
    - name: Remove template from TeXLive before caching
      run: |
        rm -Rf ${{ env.TEMPLATEDIR }}
        texhash
